export interface Candidate { name: string; tokens: string[] }

// Token guesses for public ATS boards (Greenhouse / Lever / Ashby). The probe keeps only verified hits.
export const CANDIDATES: Candidate[] = [
  { name: 'Deel', tokens: ['deel'] },
  { name: 'Remote', tokens: ['remote', 'remotecom'] },
  { name: 'Oyster', tokens: ['oyster', 'oysterhr'] },
  { name: 'GitLab', tokens: ['gitlab'] },
  { name: 'Automattic', tokens: ['automattic', 'automatticcareers'] },
  { name: 'Zapier', tokens: ['zapier'] },
  { name: 'Toptal', tokens: ['toptal'] },
  { name: 'Doist', tokens: ['doist'] },
  { name: 'Buffer', tokens: ['buffer'] },
  { name: 'Hotjar', tokens: ['hotjar'] },
  { name: 'Toggl', tokens: ['toggl'] },
  { name: 'Wikimedia', tokens: ['wikimedia', 'wikimediafoundation'] },
  { name: 'Mozilla', tokens: ['mozilla', 'mozillacorporation'] },
  { name: 'Canonical', tokens: ['canonical'] },
  { name: 'Elastic', tokens: ['elastic'] },
  { name: 'Sourcegraph', tokens: ['sourcegraph'] },
  { name: 'Airbyte', tokens: ['airbyte'] },
  { name: 'Hasura', tokens: ['hasura'] },
  { name: 'Grafana Labs', tokens: ['grafanalabs', 'grafana'] },
  { name: 'Netlify', tokens: ['netlify'] },
  { name: 'Supabase', tokens: ['supabase'] },
  { name: 'PostHog', tokens: ['posthog'] },
  { name: 'Close', tokens: ['close', 'closeio'] },
  { name: 'n8n', tokens: ['n8n'] },
  { name: 'Cal.com', tokens: ['cal', 'calcom', 'cal-com'] },
  { name: 'Plane', tokens: ['plane', 'planeso'] },
  { name: 'Appwrite', tokens: ['appwrite'] },
  { name: 'Strapi', tokens: ['strapi'] },
  { name: 'Directus', tokens: ['directus'] },
  { name: 'Twilio', tokens: ['twilio'] },
  { name: 'Vercel', tokens: ['vercel'] },
  { name: 'Clerk', tokens: ['clerk', 'clerkdev'] },
  { name: 'Resend', tokens: ['resend'] },
  { name: 'Retool', tokens: ['retool'] },
  { name: 'Linear', tokens: ['linear'] },
  { name: 'Raycast', tokens: ['raycast'] },
  { name: 'Replit', tokens: ['replit'] },
  { name: 'Modal', tokens: ['modal', 'modal-labs'] },
  { name: 'Baseten', tokens: ['baseten'] },
  { name: 'Together AI', tokens: ['togetherai', 'together-ai', 'together'] },
  { name: 'Fireworks AI', tokens: ['fireworksai', 'fireworks-ai', 'fireworks'] },
  { name: 'Anyscale', tokens: ['anyscale'] },
  { name: 'Weights & Biases', tokens: ['wandb', 'weightsandbiases', 'weights-biases'] },
  { name: 'Hugging Face', tokens: ['huggingface', 'hugging-face'] },
  { name: 'Cohere', tokens: ['cohere'] },
  { name: 'Mistral', tokens: ['mistral', 'mistralai'] },
  { name: 'ElevenLabs', tokens: ['elevenlabs'] },
  { name: 'Vapi', tokens: ['vapi'] },
  { name: 'Retell AI', tokens: ['retellai', 'retell-ai', 'retell'] },
  { name: 'Bland AI', tokens: ['blandai', 'bland-ai', 'bland'] },
  { name: 'Synthflow', tokens: ['synthflow'] },
  { name: 'Deepgram', tokens: ['deepgram'] },
  { name: 'AssemblyAI', tokens: ['assemblyai', 'assembly-ai'] },
  { name: 'Cartesia', tokens: ['cartesia'] },
  { name: 'PolyAI', tokens: ['polyai', 'poly-ai'] },
  { name: 'LiveKit', tokens: ['livekit'] },
  { name: 'Daily', tokens: ['daily', 'dailyco'] },
  { name: 'Pipecat/Daily', tokens: ['pipecat', 'daily-co'] },
  { name: 'Hume AI', tokens: ['humeai', 'hume-ai', 'hume'] },
  { name: 'Sierra', tokens: ['sierra', 'sierraai'] },
  { name: 'Decagon', tokens: ['decagon', 'decagonai'] },
  { name: 'Cresta', tokens: ['cresta'] },
  { name: 'Observe.AI', tokens: ['observeai', 'observe-ai', 'observe'] },
  { name: 'Bitso', tokens: ['bitso'] },
  { name: 'Clip', tokens: ['clip', 'clipmx'] },
  { name: 'Kavak', tokens: ['kavak'] },
  { name: 'Konfío', tokens: ['konfio'] },
  { name: 'Clara', tokens: ['clara', 'clararcorp', 'clara-mx'] },
  { name: 'Nubank', tokens: ['nubank', 'nu'] },
  { name: 'Rappi', tokens: ['rappi'] },
  { name: 'Platzi', tokens: ['platzi'] },
  { name: 'Wizeline', tokens: ['wizeline'] },
  { name: 'Nearsure', tokens: ['nearsure'] },
  { name: 'Truelogic', tokens: ['truelogic', 'true-logic'] },
  { name: 'Encora', tokens: ['encora'] },
  { name: 'Andela', tokens: ['andela'] },
  { name: 'Turing', tokens: ['turing'] },
  { name: 'Crossover', tokens: ['crossover'] },
  { name: 'Terminal', tokens: ['terminal', 'terminalio'] },
  { name: 'Revelo', tokens: ['revelo'] },
  { name: 'Oowlish', tokens: ['oowlish'] },
  { name: 'Launchpad Lab', tokens: ['launchpadlab', 'launchpad-lab', 'launchpadlabs'] },
  { name: 'Hostaway', tokens: ['hostaway'] },
  { name: 'Chainlink Labs', tokens: ['chainlinklabs', 'chainlink-labs', 'chainlink'] },
  { name: 'Kraken', tokens: ['kraken', 'kraken123', 'krakenfx'] },
  { name: 'Consensys', tokens: ['consensys'] },
  { name: 'Alchemy', tokens: ['alchemy', 'alchemyplatform'] },
  { name: 'Helius', tokens: ['helius', 'heliuslabs'] },
  { name: 'Fleetio', tokens: ['fleetio'] },
  { name: 'Dremio', tokens: ['dremio'] },
  { name: 'micro1', tokens: ['micro1'] },
  { name: 'Scalepex', tokens: ['scalepex'] },
];
